title: Добре дошли на моя експериментален сайт!
author: danny-dimitrov
email: daniel.dimitrov@xxx.com
description: > # this means to ignore newlines until "baseurl:"
  Това е проект-упражнение в рамките на обучението на GitHub за приложение на Jekyll за изработка на статични уеб сайтове.

# social links
twitter_username: DanielYDimitrov
github_username:  danny-dimitrov

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
